networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: "bitnami/mongodb:5.0"
    environment:
      - MONGODB_USERNAME=app
      - MONGODB_PASSWORD=pwd
      - MONGODB_DATABASE=db
    networks:
      - app-tier
  app:
    build: .
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - mongodb
